### ISSUE TITLE
Update Guzzle dependency to v7

### ISSUE THREAD

**Issue by daangelov** [kickboxio/kickbox-php#15]
Hello,
Are you planning on upgrading guzzlehttp/guzzle package to v7. A lot of packages now are requiring ^7.0, so it would be very nice.
Thank you!

**Comment by masonjo** [comment]
I agree this is needed.

**Comment by Jafo232** [comment]
Agreed.  Can't install without this..

**Comment by j-fulbright** [comment]
Following...

**Comment by dlondero** [comment]
Agree with the request, would be really nice to see the version bump of Guzzle w/o the need of forking only for that.

**Comment by dlondero** [comment]
@schaitanya @danhstevens would you please have time to look into #16 which would solve this as well?

**Comment by j-fulbright** [comment]
Any updates on this? Would like to be able to update some other dependencies that require Guzzle v7 but have direct conflicts with v6

**Comment by j-fulbright** [comment]
Looks like this will require a fork as it seems to be going unmaintained :( Anybody already done any updates for this?

**Comment by maurogesuitti** [comment]
I also need it

**Comment by jons** [comment]
this is now complete on `main-php7` in release tag `v3.0.0` and i'm moving on to PHP 8 (and onward) in branch `main` -- i will close this issue, but please check my work and open new issues if needed
