### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by smiffsoft** [kickboxio/kickbox-php#3]
On the 26th Feb 2015 we noticed that from 16:51 until 00:00 (GMT) we got the following response from Kickbox for every single request:

PHP Fatal error:  Uncaught exception 'Kickbox\Exception\ClientException' with message 'Insufficient balance' in /vendor/kickbox/kickbox/lib/Kickbox/HttpClient/ErrorHandler.php:49
#0 [internal function]: Kickbox\HttpClient\ErrorHandler->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))

**Comment by danhstevens** [comment]
Hey @smiffsoft. That error should only occur if you've exceeded you verification credits. Did the admin UI show that you were out of verifications by chance?

**Comment by smiffsoft** [comment]
According to the API doc it should return a HTTP code 429 if we've exceeded our credits. I would have expected the PHP API library to handle this gracefully rather than give a Fatal error which stopped our website in it's tracks.

**Comment by danhstevens** [comment]
@schaitanya perhaps the code samples should show the call wrapped in a `try/catch`?

**Comment by smiffsoft** [comment]
That would alleviate the problem, however wouldn't it be better to pass the
429 code back as a response code? The exception gives no indication of the
reason it happens so the code would be really useful to end users.

**Comment by danhstevens** [comment]
By catching the exception you should receive both the response code and the error message:

```php
try {
  $resp = $kickbox->verify("email@example.com");
 }
catch (Exception $e) {
  echo "Code: ".$e->getCode()." Message: ".$e->getMessage().PHP_EOL ;
}
```

**Comment by smiffsoft** [comment]
Great, it could easily be covered with a small documentation update then.
Thanks for your help.
