### ISSUE TITLE
Guzzle dependency

### ISSUE THREAD

**Issue by fvovan** [kickboxio/kickbox-php#6]
Hello,
I am kindly interesting if you are going to update  `"guzzle/guzzle": "3.8.*"` dependency at least to currently maintained `"guzzlehttp/guzzle": "~5.0.0"` ? 
Thank you!

**Comment by danielzev** [comment]
+1

**Comment by Hirbod** [comment]
It would be also fine to at least point to ~3.9 - i have problems with other packages that require the lasted 3 branch

**Comment by onethumb** [comment]
This is preventing us from using Kickbox (the service), too.  Please either support `guzzle 3.9+` or `guzzlehttp 6.2+`

**Comment by Hirbod** [comment]
more then 1 year and still no change. I prob. will quit using kickbox and looking for other services

**Comment by danhstevens** [comment]
This has in fact been too long in the making. My apologies. We'll take a look at upgrading guzzle and release under v2.1 shortly. We'll keep you guys posted.

**Comment by danhstevens** [comment]
Fixed in  62a5b53. Upgraded guzzle to version `3.9` for kickbox-php `v2.1.0`. We will be upgrading the upcoming `v3.0.0` to guzzlehttp ~6. Closing this issue now. Reopen if these changes are insufficient.

**Comment by rorecek** [comment]
Is it possible to support Guzzle 7, please? I'm not able to use this package with Laravel 8 because of this.
