### ISSUE TITLE
Upgrade to current stable guzzle

### ISSUE THREAD

**Issue by njam** [kickboxio/kickbox-php#8]
Currently version 6.2.2:
https://packagist.org/packages/guzzlehttp/guzzle

The library you're using now (guzzle/guzzle) is not supported anymore.
Thanks.

**Comment by marnusw** [comment]
This is causing problems for us as well at Flix Premiere. Composer clashes due to the old dependency means we can't use this library at the moment.

**Comment by tomschlick** [comment]
+1 for upgrade here. The current version is not maintained anymore

**Comment by OwenMelbz** [comment]
+1 Please sort this soon :)

**Comment by cvele** [comment]
Would you be open to accepting PR with this upgrade?
We've managed to get our composer resolve dependency. However we do not wish to keep both versions 3 and 6 in our composer.

**Comment by danhstevens** [comment]
Absolutely. PRs are most welcome.

**Comment by cvele** [comment]
@danhstevens I've sent you guys PR with upgrade.

**Comment by danhstevens** [comment]
Fixed via #10. Thanks again @cvele!
